layout_spectrum: 0.1914894
typography_spectrum: 0
color:
  lightness: 0.6276596
  brandStrength: 1
  saturation: 0.9
  rhythmicContrast: 0.4170213
  brandColors:
    - '#160D15'
    - '#A4916E'
    - '#4B301F'
    - '#FAE9E0'
name: 'The Mundane Gallery '
